package calculotochos;

import calculotochos.data.Perfil;

/**
 *
 * @author MAX
 */
public class MainForm extends javax.swing.JFrame {

    public Perfil perfil;
    private int tochoDiametro;
    private int tochoLargo;
    private int tochoLargoMax;
    private int tochoLargoMin;
    private int mesaLargoMax;
    private int contenedorDiametro;
    private int culoteLargo;
    private int mesaLargoMatrizSierra;
    private int scrapEstirador;
    private int tochoCorte = 0;
    private int tochoEspesorCorte;

    /**
     * Creates new form MainForm
     */
    public MainForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jsTochoDiametro = new javax.swing.JSlider();
        pbTochoDiametro = new javax.swing.JProgressBar();
        jtDiametro = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();
        jsTochoLargo = new javax.swing.JSlider();
        pbTochoLargo = new javax.swing.JProgressBar();
        jtLargo = new javax.swing.JSpinner();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jtLargoMaxTocho = new javax.swing.JSpinner();
        jtLargoMinTocho = new javax.swing.JSpinner();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jtLargoMaxMesa = new javax.swing.JSpinner();
        jLabel6 = new javax.swing.JLabel();
        jsCulote = new javax.swing.JSpinner();
        jLabel11 = new javax.swing.JLabel();
        jsContenedorDiametro = new javax.swing.JSpinner();
        jLabel10 = new javax.swing.JLabel();
        jsDistanciaMatrizSierra = new javax.swing.JSpinner();
        jsScrapEstirador = new javax.swing.JSpinner();
        jLabel17 = new javax.swing.JLabel();
        jsTochoEspesorCorte = new javax.swing.JSpinner();
        jLabel18 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btnPerfil = new javax.swing.JButton();
        jtPerfilID = new javax.swing.JTextField();
        jtPerfilNombre = new javax.swing.JTextField();
        jtPerfilArea = new javax.swing.JTextField();
        jtPerfilSalidas = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jtPerfilLargoComercial = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jtPerfilLargoTocho = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        btnCalcular = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jlLargoTocho = new javax.swing.JLabel();
        jlBarrasTocho = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jlSobranteTocho = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jlCulotePeso = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jlPerfilPesoXm = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jlTochosBarra = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jlBarrasSalida = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jlPesoBarra = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculo de Corte de Tochos v1.0 by MAX");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Propiedades del Tocho", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        jLabel1.setText("Diametro (mm):");

        jsTochoDiametro.setMaximum(300);
        jsTochoDiametro.setValue(152);
        jsTochoDiametro.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jsTochoDiametroStateChanged(evt);
            }
        });

        pbTochoDiametro.setMaximum(300);
        pbTochoDiametro.setValue(jsTochoDiametro.getValue());

        jtDiametro.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(152), null, Integer.valueOf(300), Integer.valueOf(1)));
        jtDiametro.setValue(jsTochoDiametro.getValue()
        );
        jtDiametro.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jtDiametroStateChanged(evt);
            }
        });

        jLabel2.setText("Largo (mm):");

        jsTochoLargo.setMaximum(6000);
        jsTochoLargo.setToolTipText("");
        jsTochoLargo.setValue(5800);
        jsTochoLargo.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jsTochoLargoStateChanged(evt);
                jsTochoLargoStateChanged1(evt);
            }
        });

        pbTochoLargo.setMaximum(6000);
        pbTochoLargo.setValue(jsTochoLargo.getValue());

        jtLargo.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(5800), null, Integer.valueOf(6000), Integer.valueOf(1)));
        jtLargo.setValue(jsTochoLargo.getValue()
        );
        jtLargo.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jtLargoStateChanged(evt);
                jtLargoStateChanged1(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(pbTochoDiametro, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                    .addComponent(jsTochoDiametro, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(pbTochoLargo, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jsTochoLargo, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtDiametro, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jtLargo, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pbTochoDiametro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jsTochoDiametro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jtDiametro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(pbTochoLargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jsTochoLargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jtLargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Propiedades de la Planta", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        jLabel3.setText("Largo maximo del Tocho (mm):");

        jtLargoMaxTocho.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(600), null, Integer.valueOf(600), Integer.valueOf(1)));

        jtLargoMinTocho.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(400), null, Integer.valueOf(600), Integer.valueOf(1)));

        jLabel4.setText("Largo minimo del Tocho (mm):");

        jLabel5.setText("Largo maximo de Mesa (mm):");

        jtLargoMaxMesa.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(32000), null, Integer.valueOf(37500), Integer.valueOf(1)));

        jLabel6.setText("Largo del Culotede Tocho (mm):");

        jsCulote.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(20), null, Integer.valueOf(50), Integer.valueOf(1)));

        jLabel11.setText("Diametro del Contenedor (mm):");

        jsContenedorDiametro.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(159), null, Integer.valueOf(300), Integer.valueOf(1)));

        jLabel10.setText("Distancia Matriz Corte (mm):");

        jsDistanciaMatrizSierra.setModel(new javax.swing.SpinnerNumberModel(6750, 6000, 10000, 1));

        jsScrapEstirador.setModel(new javax.swing.SpinnerNumberModel(600, 0, 3000, 1));

        jLabel17.setText("Scrap por estirador y corte (mm):");

        jsTochoEspesorCorte.setModel(new javax.swing.SpinnerNumberModel(1, 1, 6, 1));

        jLabel18.setText("Espesor Corte Tocho (mm):");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jsScrapEstirador)
                    .addComponent(jsDistanciaMatrizSierra)
                    .addComponent(jsCulote)
                    .addComponent(jtLargoMaxTocho)
                    .addComponent(jtLargoMinTocho)
                    .addComponent(jtLargoMaxMesa)
                    .addComponent(jsContenedorDiametro)
                    .addComponent(jsTochoEspesorCorte))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtLargoMaxTocho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jtLargoMinTocho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtLargoMaxMesa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jsContenedorDiametro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jsCulote, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jsDistanciaMatrizSierra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jsScrapEstirador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jsTochoEspesorCorte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Propiedades de la Matriz", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        btnPerfil.setText("Buscar");
        btnPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPerfilActionPerformed(evt);
            }
        });

        jtPerfilID.setEditable(false);

        jtPerfilNombre.setEditable(false);

        jtPerfilArea.setEditable(false);

        jtPerfilSalidas.setEditable(false);

        jLabel7.setText("Codigo");

        jLabel8.setText("Nombre");

        jLabel9.setText("Area");

        jLabel21.setText("Salidas");

        jtPerfilLargoComercial.setEditable(false);

        jLabel23.setText("Largo Comercial");

        jLabel24.setText("Largo Tocho");

        jtPerfilLargoTocho.setEditable(false);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jtPerfilLargoComercial))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jtPerfilLargoTocho, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnPerfil))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtPerfilID, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtPerfilNombre)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(0, 102, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtPerfilArea, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel21)
                            .addComponent(jtPerfilSalidas, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel21))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtPerfilID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtPerfilNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtPerfilArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtPerfilSalidas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel23)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtPerfilLargoComercial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnPerfil)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel24)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtPerfilLargoTocho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(10, 10, 10))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Calculos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        btnCalcular.setText("Calcular");
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });

        jLabel12.setText("Largo de Tocho (mm):");

        jlLargoTocho.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jlLargoTocho.setForeground(new java.awt.Color(0, 102, 255));
        jlLargoTocho.setText("0");

        jlBarrasTocho.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jlBarrasTocho.setForeground(new java.awt.Color(0, 102, 255));
        jlBarrasTocho.setText("0");

        jLabel13.setText("Total de Barras por Tocho:");

        jlSobranteTocho.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jlSobranteTocho.setForeground(new java.awt.Color(255, 102, 102));
        jlSobranteTocho.setText("0");

        jLabel14.setText("Sobrante Corte Barra Tocho (mm):");

        jLabel15.setText("Desperdicio Culote (gr):");

        jlCulotePeso.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jlCulotePeso.setForeground(new java.awt.Color(255, 102, 102));
        jlCulotePeso.setText("0");

        jLabel16.setText("Peso del Perfil (gr/m):");

        jlPerfilPesoXm.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jlPerfilPesoXm.setForeground(new java.awt.Color(0, 102, 255));
        jlPerfilPesoXm.setText("0");

        jLabel19.setText("Cantidad de Tochos por Barra:");

        jlTochosBarra.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jlTochosBarra.setForeground(new java.awt.Color(0, 102, 255));
        jlTochosBarra.setText("0");

        jLabel20.setText("Total Barras por Salida:");

        jlBarrasSalida.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jlBarrasSalida.setForeground(new java.awt.Color(0, 102, 255));
        jlBarrasSalida.setText("0");

        jLabel22.setText("Peso por Barra (Kg.):");

        jlPesoBarra.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jlPesoBarra.setForeground(new java.awt.Color(0, 102, 255));
        jlPesoBarra.setText("0");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnCalcular, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel19, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlCulotePeso)
                            .addComponent(jlTochosBarra)
                            .addComponent(jlLargoTocho)
                            .addComponent(jlSobranteTocho))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 143, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jlPerfilPesoXm))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel20)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel22))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jlBarrasTocho)
                                    .addComponent(jlBarrasSalida)
                                    .addComponent(jlPesoBarra))))
                        .addGap(0, 138, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(btnCalcular)
                .addGap(28, 28, 28)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jlLargoTocho)
                    .addComponent(jLabel16)
                    .addComponent(jlPerfilPesoXm))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(jlTochosBarra)
                    .addComponent(jlPesoBarra)
                    .addComponent(jLabel22))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(jlSobranteTocho))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(jlCulotePeso)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(jlBarrasTocho))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel20)
                            .addComponent(jlBarrasSalida))))
                .addGap(0, 63, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jsTochoDiametroStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jsTochoDiametroStateChanged
        pbTochoDiametro.setValue(jsTochoDiametro.getValue());
        jtDiametro.setValue(jsTochoDiametro.getValue());
    }//GEN-LAST:event_jsTochoDiametroStateChanged

    private void jtDiametroStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jtDiametroStateChanged
        jsTochoDiametro.setValue((int) jtDiametro.getValue());
    }//GEN-LAST:event_jtDiametroStateChanged

    private void jsTochoLargoStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jsTochoLargoStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jsTochoLargoStateChanged

    private void jtLargoStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jtLargoStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jtLargoStateChanged

    private void jsTochoLargoStateChanged1(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jsTochoLargoStateChanged1
        pbTochoLargo.setValue(jsTochoLargo.getValue());
        jtLargo.setValue(jsTochoLargo.getValue());
    }//GEN-LAST:event_jsTochoLargoStateChanged1

    private void jtLargoStateChanged1(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jtLargoStateChanged1
        jsTochoLargo.setValue((int) jtLargo.getValue());
    }//GEN-LAST:event_jtLargoStateChanged1

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
        if (perfil != null) {
            getData();
            double tochoArea;
            double tochoPesoXmm;
            double contenedorArea;
            double culotePeso;
            int barrasMesa;
            int barraProduccion;

            //Calculo el peso del Tocho por mm
            tochoArea = Utils.areaCirculo(tochoDiametro);
            tochoPesoXmm = tochoArea * Utils.DEN_AL_6063;
            //Calculo el peso total del Culote
            contenedorArea = Utils.areaCirculo(contenedorDiametro);
            culotePeso = (contenedorArea * Utils.DEN_AL_6063) * culoteLargo;
            // Calculo la cantidad maxima de barras que entran en la mesa mas scrap
            barrasMesa = (int) (mesaLargoMax - scrapEstirador) / perfil.getLargoComercial();
            barraProduccion = barrasMesa * perfil.getLargoComercial() + scrapEstirador;
            //Calculando Tocho
            while ((Utils.calcularPeso(barraProduccion, perfil.getArea()) * perfil.getSalidas()) > (Utils.calcularPeso(tochoLargoMax, tochoArea) - culotePeso)) {
                barrasMesa--;
                barraProduccion = barrasMesa * perfil.getLargoComercial() + scrapEstirador;
            }
            double pesoBarraProduccion = (perfil.getPeso(barraProduccion)) * perfil.getSalidas();
            tochoCorte = (int) ((pesoBarraProduccion + culotePeso) / tochoPesoXmm);
            //Mostrando Resultados
            jlCulotePeso.setText(Utils.round(culotePeso, 3));
            jlPerfilPesoXm.setText(Utils.round(perfil.getPeso(1000), 3));
            jlSobranteTocho.setText(Integer.toString(tochoLargo - (((int) (tochoLargo / tochoCorte)) * (tochoCorte + tochoEspesorCorte))));
            jlLargoTocho.setText(Integer.toString(tochoCorte));
            jlBarrasTocho.setText(Integer.toString(barrasMesa * perfil.getSalidas()));
            jlTochosBarra.setText(Integer.toString((int) (tochoLargo / tochoCorte)));
            jlBarrasSalida.setText(Integer.toString(barrasMesa));
            jlPesoBarra.setText(Utils.round(perfil.getPeso(perfil.getLargoComercial()) / 1000, 3));
        }
    }//GEN-LAST:event_btnCalcularActionPerformed

    private void btnPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPerfilActionPerformed
        PerfilesABM ventana = new PerfilesABM(this);
        ventana.setVisible(true);
        setData();

    }//GEN-LAST:event_btnPerfilActionPerformed

    private void setData() {
        jtPerfilID.setText(perfil.getId());
        jtPerfilNombre.setText(perfil.getNombre());
        jtPerfilArea.setText(Double.toString(perfil.getArea()));
        jtPerfilSalidas.setText(Integer.toString(perfil.getSalidas()));
        jtPerfilLargoComercial.setText(Integer.toString(perfil.getLargoComercial()));
        jtPerfilLargoTocho.setText(Integer.toString(perfil.getTochoMedida()));
    }

    private void getData() {
        tochoDiametro = (int) jtDiametro.getValue();
        tochoLargo = (int) jtLargo.getValue();
        tochoLargoMax = (int) jtLargoMaxTocho.getValue();
        tochoLargoMin = (int) jtLargoMinTocho.getValue();
        mesaLargoMax = (int) jtLargoMaxMesa.getValue();
        mesaLargoMatrizSierra = (int) jsDistanciaMatrizSierra.getValue();
        contenedorDiametro = (int) jsContenedorDiametro.getValue();
        culoteLargo = (int) jsCulote.getValue();
        scrapEstirador = (int) jsScrapEstirador.getValue();
        tochoEspesorCorte = (int) jsTochoEspesorCorte.getValue();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
            }
        });
    }
// <editor-fold defaultstate="collapsed" desc=" Variables autogeneradas ">
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcular;
    private javax.swing.JButton btnPerfil;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel jlBarrasSalida;
    private javax.swing.JLabel jlBarrasTocho;
    private javax.swing.JLabel jlCulotePeso;
    private javax.swing.JLabel jlLargoTocho;
    private javax.swing.JLabel jlPerfilPesoXm;
    private javax.swing.JLabel jlPesoBarra;
    private javax.swing.JLabel jlSobranteTocho;
    private javax.swing.JLabel jlTochosBarra;
    private javax.swing.JSpinner jsContenedorDiametro;
    private javax.swing.JSpinner jsCulote;
    private javax.swing.JSpinner jsDistanciaMatrizSierra;
    private javax.swing.JSpinner jsScrapEstirador;
    private javax.swing.JSlider jsTochoDiametro;
    private javax.swing.JSpinner jsTochoEspesorCorte;
    private javax.swing.JSlider jsTochoLargo;
    private javax.swing.JSpinner jtDiametro;
    private javax.swing.JSpinner jtLargo;
    private javax.swing.JSpinner jtLargoMaxMesa;
    private javax.swing.JSpinner jtLargoMaxTocho;
    private javax.swing.JSpinner jtLargoMinTocho;
    private javax.swing.JTextField jtPerfilArea;
    private javax.swing.JTextField jtPerfilID;
    private javax.swing.JTextField jtPerfilLargoComercial;
    private javax.swing.JTextField jtPerfilLargoTocho;
    private javax.swing.JTextField jtPerfilNombre;
    private javax.swing.JTextField jtPerfilSalidas;
    private javax.swing.JProgressBar pbTochoDiametro;
    private javax.swing.JProgressBar pbTochoLargo;
    // End of variables declaration//GEN-END:variables
//</editor-fold>
}
